package pl.mealcore.dto.product;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import pl.mealcore.dto.BaseDto;
import pl.mealcore.model.product.NutrientsEntity;

@Data
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
public class Nutrients extends BaseDto<NutrientsEntity> {

    private Long productId;
    private String energyKj;
    private String energyKcal;
    private String energy;
    private String energyFromFat;
    private String fat;
    private String saturatedFat;
    private String butyricAcid;
    private String caproicAcid;
    private String caprylicAcid;
    private String capricAcid;
    private String lauricAcid;
    private String myristicAcid;
    private String palmiticAcid;
    private String stearicAcid;
    private String arachidicAcid;
    private String behenicAcid;
    private String lignocericAcid;
    private String ceroticAcid;
    private String montanicAcid;
    private String melissicAcid;
    private String monounsaturatedFat;
    private String polyunsaturatedFat;
    private String omega3Fat;
    private String alphaLinolenicAcid;
    private String eicosapentaenoicAcid;
    private String docosahexaenoicAcid;
    private String omega6Fat;
    private String linoleicAcid;
    private String arachidonicAcid;
    private String gammaLinolenicAcid;
    private String dihomoGammaLinolenicAcid;
    private String omega9Fat;
    private String oleicAcid;
    private String elaidicAcid;
    private String gondoicAcid;
    private String meadAcid;
    private String erucicAcid;
    private String nervonicAcid;
    private String transFat;
    private String cholesterol;
    private String carbohydrates;
    private String sugars;
    private String sucrose;
    private String glucose;
    private String fructose;
    private String lactose;
    private String maltose;
    private String maltodextrins;
    private String starch;
    private String polyols;
    private String fiber;
    private String solubleFiber;
    private String insolubleFiber;
    private String proteins;
    private String casein;
    private String serumProteins;
    private String nucleotides;
    private String salt;
    private String sodium;
    private String alcohol;
    private String vitaminA;
    private String betaCarotene;
    private String vitaminD;
    private String vitaminE;
    private String vitaminK;
    private String vitaminC;
    private String vitaminB1;
    private String vitaminB2;
    private String vitaminPp;
    private String vitaminB6;
    private String vitaminB9;
    private String folates;
    private String vitaminB12;
    private String biotin;
    private String pantothenicAcid;
    private String silica;
    private String bicarbonate;
    private String potassium;
    private String chloride;
    private String calcium;
    private String phosphorus;
    private String iron;
    private String magnesium;
    private String zinc;
    private String copper;
    private String manganese;
    private String fluoride;
    private String selenium;
    private String chromium;
    private String molybdenum;
    private String iodine;
    private String caffeine;
    private String taurine;
    private String ph;
    private String fruitsVegetablesNuts;
    private String fruitsVegetablesNutsDried;
    private String fruitsVegetablesNutsEstimate;
    private String collagenMeatProteinRatio;
    private String cocoa;
    private String chlorophyl;
    private String carbonFootprint;
    private String carbonFootprintFromMeatOrFish;
    private String glycemicIndex;
    private String waterHardness;
    private String choline;
    private String phylloquinone;
    private String betaGlucan;
    private String inositol;
    private String carnitine;

    public Nutrients(NutrientsEntity entity) {
        super(entity);
        this.productId = entity.getProductId();
        this.energyKj = entity.getEnergy_kj_100g();
        this.energyKcal = entity.getEnergy_kcal_100g();
        this.energy = entity.getEnergy_100g();
        this.energyFromFat = entity.getEnergy_from_fat_100g();
        this.fat = entity.getFat_100g();
        this.saturatedFat = entity.getSaturated_fat_100g();
        this.butyricAcid = entity.getButyric_acid_100g();
        this.caproicAcid = entity.getCaproic_acid_100g();
        this.caprylicAcid = entity.getCaprylic_acid_100g();
        this.capricAcid = entity.getCapric_acid_100g();
        this.lauricAcid = entity.getLauric_acid_100g();
        this.myristicAcid = entity.getMyristic_acid_100g();
        this.palmiticAcid = entity.getPalmitic_acid_100g();
        this.stearicAcid = entity.getStearic_acid_100g();
        this.arachidicAcid = entity.getArachidic_acid_100g();
        this.behenicAcid = entity.getBehenic_acid_100g();
        this.lignocericAcid = entity.getLignoceric_acid_100g();
        this.ceroticAcid = entity.getCerotic_acid_100g();
        this.montanicAcid = entity.getMontanic_acid_100g();
        this.melissicAcid = entity.getMelissic_acid_100g();
        this.monounsaturatedFat = entity.getMonounsaturated_fat_100g();
        this.polyunsaturatedFat = entity.getPolyunsaturated_fat_100g();
        this.omega3Fat = entity.getOmega_3_fat_100g();
        this.alphaLinolenicAcid = entity.getAlpha_linolenic_acid_100g();
        this.eicosapentaenoicAcid = entity.getEicosapentaenoic_acid_100g();
        this.docosahexaenoicAcid = entity.getDocosahexaenoic_acid_100g();
        this.omega6Fat = entity.getOmega_6_fat_100g();
        this.linoleicAcid = entity.getLinoleic_acid_100g();
        this.arachidonicAcid = entity.getArachidonic_acid_100g();
        this.gammaLinolenicAcid = entity.getGamma_linolenic_acid_100g();
        this.dihomoGammaLinolenicAcid = entity.getDihomo_gamma_linolenic_acid_100g();
        this.omega9Fat = entity.getOmega_9_fat_100g();
        this.oleicAcid = entity.getOleic_acid_100g();
        this.elaidicAcid = entity.getElaidic_acid_100g();
        this.gondoicAcid = entity.getGondoic_acid_100g();
        this.meadAcid = entity.getMead_acid_100g();
        this.erucicAcid = entity.getErucic_acid_100g();
        this.nervonicAcid = entity.getNervonic_acid_100g();
        this.transFat = entity.getTrans_fat_100g();
        this.cholesterol = entity.getCholesterol_100g();
        this.carbohydrates = entity.getCarbohydrates_100g();
        this.sugars = entity.getSugars_100g();
        this.sucrose = entity.getSucrose_100g();
        this.glucose = entity.getGlucose_100g();
        this.fructose = entity.getFructose_100g();
        this.lactose = entity.getLactose_100g();
        this.maltose = entity.getMaltose_100g();
        this.maltodextrins = entity.getMaltodextrins_100g();
        this.starch = entity.getStarch_100g();
        this.polyols = entity.getPolyols_100g();
        this.fiber = entity.getFiber_100g();
        this.solubleFiber = entity.getSoluble_fiber_100g();
        this.insolubleFiber = entity.getInsoluble_fiber_100g();
        this.proteins = entity.getProteins_100g();
        this.casein = entity.getCasein_100g();
        this.serumProteins = entity.getSerum_proteins_100g();
        this.nucleotides = entity.getNucleotides_100g();
        this.salt = entity.getSalt_100g();
        this.sodium = entity.getSodium_100g();
        this.alcohol = entity.getAlcohol_100g();
        this.vitaminA = entity.getVitamin_a_100g();
        this.betaCarotene = entity.getBeta_carotene_100g();
        this.vitaminD = entity.getVitamin_d_100g();
        this.vitaminE = entity.getVitamin_e_100g();
        this.vitaminK = entity.getVitamin_k_100g();
        this.vitaminC = entity.getVitamin_c_100g();
        this.vitaminB1 = entity.getVitamin_b1_100g();
        this.vitaminB2 = entity.getVitamin_b2_100g();
        this.vitaminPp = entity.getVitamin_pp_100g();
        this.vitaminB6 = entity.getVitamin_b6_100g();
        this.vitaminB9 = entity.getVitamin_b9_100g();
        this.folates = entity.getFolates_100g();
        this.vitaminB12 = entity.getVitamin_b12_100g();
        this.biotin = entity.getBiotin_100g();
        this.pantothenicAcid = entity.getPantothenic_acid_100g();
        this.silica = entity.getSilica_100g();
        this.bicarbonate = entity.getBicarbonate_100g();
        this.potassium = entity.getPotassium_100g();
        this.chloride = entity.getChloride_100g();
        this.calcium = entity.getCalcium_100g();
        this.phosphorus = entity.getPhosphorus_100g();
        this.iron = entity.getIron_100g();
        this.magnesium = entity.getMagnesium_100g();
        this.zinc = entity.getZinc_100g();
        this.copper = entity.getCopper_100g();
        this.manganese = entity.getManganese_100g();
        this.fluoride = entity.getFluoride_100g();
        this.selenium = entity.getSelenium_100g();
        this.chromium = entity.getChromium_100g();
        this.molybdenum = entity.getMolybdenum_100g();
        this.iodine = entity.getIodine_100g();
        this.caffeine = entity.getCaffeine_100g();
        this.taurine = entity.getTaurine_100g();
        this.ph = entity.getPh_100g();
        this.fruitsVegetablesNuts = entity.getFruits_vegetables_nuts_100g();
        this.fruitsVegetablesNutsDried = entity.getFruits_vegetables_nuts_dried_100g();
        this.fruitsVegetablesNutsEstimate = entity.getFruits_vegetables_nuts_estimate_100g();
        this.collagenMeatProteinRatio = entity.getCollagen_meat_protein_ratio_100g();
        this.cocoa = entity.getCocoa_100g();
        this.chlorophyl = entity.getChlorophyl_100g();
        this.carbonFootprint = entity.getCarbon_footprint_100g();
        this.carbonFootprintFromMeatOrFish = entity.getCarbon_footprint_from_meat_or_fish_100g();
        this.glycemicIndex = entity.getGlycemic_index_100g();
        this.waterHardness = entity.getWater_hardness_100g();
        this.choline = entity.getCholine_100g();
        this.phylloquinone = entity.getPhylloquinone_100g();
        this.betaGlucan = entity.getBeta_glucan_100g();
        this.inositol = entity.getInositol_100g();
        this.carnitine = entity.getCarnitine_100g();
    }

    @Override
    public NutrientsEntity toEntity() {
        NutrientsEntity entity = new NutrientsEntity();
        entity.setId(id);
        entity.setProductId(productId);
        entity.setEnergy_kj_100g(energyKj);
        entity.setEnergy_kcal_100g(energyKcal);
        entity.setEnergy_100g(energy);
        entity.setEnergy_from_fat_100g(energyFromFat);
        entity.setFat_100g(fat);
        entity.setSaturated_fat_100g(saturatedFat);
        entity.setButyric_acid_100g(butyricAcid);
        entity.setCaproic_acid_100g(caproicAcid);
        entity.setCaprylic_acid_100g(caprylicAcid);
        entity.setCapric_acid_100g(capricAcid);
        entity.setLauric_acid_100g(lauricAcid);
        entity.setMyristic_acid_100g(myristicAcid);
        entity.setPalmitic_acid_100g(palmiticAcid);
        entity.setStearic_acid_100g(stearicAcid);
        entity.setArachidic_acid_100g(arachidicAcid);
        entity.setBehenic_acid_100g(behenicAcid);
        entity.setLignoceric_acid_100g(lignocericAcid);
        entity.setCerotic_acid_100g(ceroticAcid);
        entity.setMontanic_acid_100g(montanicAcid);
        entity.setMelissic_acid_100g(melissicAcid);
        entity.setMonounsaturated_fat_100g(monounsaturatedFat);
        entity.setPolyunsaturated_fat_100g(polyunsaturatedFat);
        entity.setOmega_3_fat_100g(omega3Fat);
        entity.setAlpha_linolenic_acid_100g(alphaLinolenicAcid);
        entity.setEicosapentaenoic_acid_100g(eicosapentaenoicAcid);
        entity.setDocosahexaenoic_acid_100g(docosahexaenoicAcid);
        entity.setOmega_6_fat_100g(omega6Fat);
        entity.setLinoleic_acid_100g(linoleicAcid);
        entity.setArachidonic_acid_100g(arachidonicAcid);
        entity.setGamma_linolenic_acid_100g(gammaLinolenicAcid);
        entity.setDihomo_gamma_linolenic_acid_100g(dihomoGammaLinolenicAcid);
        entity.setOmega_9_fat_100g(omega9Fat);
        entity.setOleic_acid_100g(oleicAcid);
        entity.setElaidic_acid_100g(elaidicAcid);
        entity.setGondoic_acid_100g(gondoicAcid);
        entity.setMead_acid_100g(meadAcid);
        entity.setErucic_acid_100g(erucicAcid);
        entity.setNervonic_acid_100g(nervonicAcid);
        entity.setTrans_fat_100g(transFat);
        entity.setCholesterol_100g(cholesterol);
        entity.setCarbohydrates_100g(carbohydrates);
        entity.setSugars_100g(sugars);
        entity.setSucrose_100g(sucrose);
        entity.setGlucose_100g(glucose);
        entity.setFructose_100g(fructose);
        entity.setLactose_100g(lactose);
        entity.setMaltose_100g(maltose);
        entity.setMaltodextrins_100g(maltodextrins);
        entity.setStarch_100g(starch);
        entity.setPolyols_100g(polyols);
        entity.setFiber_100g(fiber);
        entity.setSoluble_fiber_100g(solubleFiber);
        entity.setInsoluble_fiber_100g(insolubleFiber);
        entity.setProteins_100g(proteins);
        entity.setCasein_100g(casein);
        entity.setSerum_proteins_100g(serumProteins);
        entity.setNucleotides_100g(nucleotides);
        entity.setSalt_100g(salt);
        entity.setSodium_100g(sodium);
        entity.setAlcohol_100g(sodium);
        entity.setVitamin_a_100g(vitaminA);
        entity.setBeta_carotene_100g(betaCarotene);
        entity.setVitamin_d_100g(vitaminD);
        entity.setVitamin_e_100g(vitaminE);
        entity.setVitamin_k_100g(vitaminK);
        entity.setVitamin_c_100g(vitaminC);
        entity.setVitamin_b1_100g(vitaminB1);
        entity.setVitamin_b2_100g(vitaminB2);
        entity.setVitamin_pp_100g(vitaminPp);
        entity.setVitamin_b6_100g(vitaminB6);
        entity.setVitamin_b9_100g(vitaminB9);
        entity.setFolates_100g(folates);
        entity.setVitamin_b12_100g(vitaminB12);
        entity.setBiotin_100g(biotin);
        entity.setPantothenic_acid_100g(pantothenicAcid);
        entity.setSilica_100g(silica);
        entity.setBicarbonate_100g(bicarbonate);
        entity.setPotassium_100g(potassium);
        entity.setChloride_100g(chloride);
        entity.setCalcium_100g(calcium);
        entity.setPhosphorus_100g(phosphorus);
        entity.setIron_100g(iron);
        entity.setMagnesium_100g(magnesium);
        entity.setZinc_100g(zinc);
        entity.setCopper_100g(copper);
        entity.setManganese_100g(manganese);
        entity.setFluoride_100g(fluoride);
        entity.setSelenium_100g(selenium);
        entity.setChromium_100g(chromium);
        entity.setMolybdenum_100g(molybdenum);
        entity.setIodine_100g(iodine);
        entity.setCaffeine_100g(caffeine);
        entity.setTaurine_100g(taurine);
        entity.setPh_100g(ph);
        entity.setFruits_vegetables_nuts_100g(fruitsVegetablesNuts);
        entity.setFruits_vegetables_nuts_dried_100g(fruitsVegetablesNutsDried);
        entity.setFruits_vegetables_nuts_estimate_100g(fruitsVegetablesNutsEstimate);
        entity.setCollagen_meat_protein_ratio_100g(collagenMeatProteinRatio);
        entity.setCocoa_100g(cocoa);
        entity.setChlorophyl_100g(chlorophyl);
        entity.setCarbon_footprint_100g(carbonFootprint);
        entity.setCarbon_footprint_from_meat_or_fish_100g(carbonFootprintFromMeatOrFish);
        entity.setGlycemic_index_100g(glycemicIndex);
        entity.setWater_hardness_100g(waterHardness);
        entity.setCholine_100g(choline);
        entity.setPhylloquinone_100g(phylloquinone);
        entity.setBeta_glucan_100g(betaGlucan);
        entity.setInositol_100g(inositol);
        entity.setCarnitine_100g(carnitine);
        return entity;
    }
}
