package pl.mealcore.dto.statistic;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class StatisticNutrients {

    private Date date;
    private double energyKj;
    private double energyKcal;
    private double energy;
    private double energyFromFat;
    private double fat;
    private double saturatedFat;
    private double butyricAcid;
    private double caproicAcid;
    private double caprylicAcid;
    private double capricAcid;
    private double lauricAcid;
    private double myristicAcid;
    private double palmiticAcid;
    private double stearicAcid;
    private double arachidicAcid;
    private double behenicAcid;
    private double lignocericAcid;
    private double ceroticAcid;
    private double montanicAcid;
    private double melissicAcid;
    private double monounsaturatedFat;
    private double polyunsaturatedFat;
    private double omega3Fat;
    private double alphaLinolenicAcid;
    private double eicosapentaenoicAcid;
    private double docosahexaenoicAcid;
    private double omega6Fat;
    private double linoleicAcid;
    private double arachidonicAcid;
    private double gammaLinolenicAcid;
    private double dihomoGammaLinolenicAcid;
    private double omega9Fat;
    private double oleicAcid;
    private double elaidicAcid;
    private double gondoicAcid;
    private double meadAcid;
    private double erucicAcid;
    private double nervonicAcid;
    private double transFat;
    private double cholesterol;
    private double carbohydrates;
    private double sugars;
    private double sucrose;
    private double glucose;
    private double fructose;
    private double lactose;
    private double maltose;
    private double maltodextrins;
    private double starch;
    private double polyols;
    private double fiber;
    private double solubleFiber;
    private double insolubleFiber;
    private double proteins;
    private double casein;
    private double serumProteins;
    private double nucleotides;
    private double salt;
    private double sodium;
    private double alcohol;
    private double vitaminA;
    private double betaCarotene;
    private double vitaminD;
    private double vitaminE;
    private double vitaminK;
    private double vitaminC;
    private double vitaminB1;
    private double vitaminB2;
    private double vitaminPp;
    private double vitaminB6;
    private double vitaminB9;
    private double folates;
    private double vitaminB12;
    private double biotin;
    private double pantothenicAcid;
    private double silica;
    private double bicarbonate;
    private double potassium;
    private double chloride;
    private double calcium;
    private double phosphorus;
    private double iron;
    private double magnesium;
    private double zinc;
    private double copper;
    private double manganese;
    private double fluoride;
    private double selenium;
    private double chromium;
    private double molybdenum;
    private double iodine;
    private double caffeine;
    private double taurine;
    private double ph;
    private double fruitsVegetablesNuts;
    private double fruitsVegetablesNutsDried;
    private double fruitsVegetablesNutsEstimate;
    private double collagenMeatProteinRatio;
    private double cocoa;
    private double chlorophyl;
    private double carbonFootprint;
    private double carbonFootprintFromMeatOrFish;
    private double glycemicIndex;
    private double waterHardness;
    private double choline;
    private double phylloquinone;
    private double betaGlucan;
    private double inositol;
    private double carnitine;

}
